import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shoplyapp/features/presentation/pages/Auth%20pages/enter_otp_page.dart';
import 'package:shoplyapp/features/presentation/pages/home_page.dart';
// 👈 The configuration file generated by flutterfire configure
import 'firebase_options.dart';

void main() async {
  // Ensure the native components are ready before starting the app
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the generated platform-specific options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: EnterOtpPage());
  }
}
