// import 'package:hive_flutter/hive_flutter.dart'; // Uncomment when ready

// --- Core Imports ---
import 'firebase_options.dart'; // Generated by FlutterFire
import 'core/di/injection_container.dart' as di; // Dependency Injection
import 'core/router/app_router.dart'; // GoRouter Config
import 'core/theme/app_theme.dart'; // App Theme
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

// --- File Imports ---
import 'package:shoplyapp/features/AUTH/presentation/bloc/auth_bloc.dart';

void main() async {
  // 1. Ensure native bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Initialize Dependency Injection (GetIt)
  await di.initDependencies();

  // --- HIVE INITIALIZATION ---
  // await Hive.initFlutter();
  // Hive.registerAdapter(ProductModelAdapter());
  // await Hive.openBox<CartItemModel>('cart_box');
  // ---------------------------

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // 1. Get the AuthBloc instance from Service Locator
    // We create it here so we can pass the SAME instance to both the Router and the Provider
    final authBloc = di.sl<AuthBloc>();

    // 2. Trigger the "Check Status" event immediately
    // This starts the logic: Splash -> Check Local Storage -> Check Firebase
    authBloc.add(AuthCheckStatus());

    // 3. Initialize the Router with the AuthBloc
    final appRouter = AppRouter(authBloc);

    return MultiBlocProvider(
      providers: [
        // 4. Provide the AuthBloc to the widget tree
        // We use 'create' to simply return the instance we already grabbed
        BlocProvider<AuthBloc>(
          create: (_) => authBloc,
        ),
      ],
      child: MaterialApp.router(
        debugShowCheckedModeBanner: false,

        // Theme Configuration
        theme: AppTheme.lightTheme,

        // == ROUTER CONFIGURATION ==
        // We access the 'router' property of your AppRouter class
        routerConfig: appRouter.router, 
      ),
    );
  }
}